### ISSUE TITLE
Warning: java.util.ConcurrentModificationException - CraftScheduler Thread 426 / Task 7992905

### ISSUE THREAD

**Issue by TheDGOfficial** [ChestShop-authors/ChestShop-3#101]
#### Plugin Version
3.9.1-SNAPSHOT (build 59)
 
#### Plugin Config
Not necessary.
 
#### Server Version
git-PaperSpigot-1f7d532 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
 
#### Server Log
Not necessary for full log. I have one warning about ConcurrentModificationException.

```
[13:32:14] [Craft Scheduler Thread - 426/WARN]: Exception in thread "Craft Scheduler Thread - 426" 
[13:32:14] [Craft Scheduler Thread - 426/WARN]: org.apache.commons.lang.UnhandledException: Plugin ChestShop v3.9.1-SNAPSHOT (build 59) generated an exception while executing task 7992905
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:142)
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:145)
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:146)
	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:108)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:272)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:262)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:234)
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:209)
	at com.Acrobot.ChestShop.Metadata.ItemDatabase.getItemCode(ItemDatabase.java:50)
	at com.Acrobot.Breeze.Utils.MaterialUtil$Metadata.getItemCode(MaterialUtil.java:386)
	at com.Acrobot.Breeze.Utils.MaterialUtil.getSignName(MaterialUtil.java:160)
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionLogger$1.run(TransactionLogger.java:32)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

#### What other plugins are you running?
Not necessary

#### What is happening?
I opened my log file and checked it for errors & warnings and i've found this warning.

#### What did you expect to happen?
Not necessary

Please provide any additional info below

ChestShop throws a error i don't know the reason or how to fix this errors.

**Comment by Phoenix616** [comment]
Most likely fixed in that commit. Imo. the issue was that it tried to access and dump ItemStack information in an async thread. The current logging code should be rather cheap so doing it on the main thread should not lead to any issue.
