### ISSUE TITLE
NoSuchFieldError: BANNER in 1.7.10 with latest build

### ISSUE THREAD

**Issue by TheDGOfficial** [ChestShop-authors/ChestShop-3#115]
#### Plugin Version
v3.9.1-SNAPSHOT (build 65)

#### Server Version
PaperSpigot 1.7.10

#### Server Log
```
[16:05:57] [Server thread/ERROR]: Could not pass event TransactionEvent to ChestShop v3.9.1-SNAPSHOT (build 65)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:133) [ChestShop.jar:?]
	at sun.reflect.GeneratedMethodAccessor176.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:382) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:666) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.NoSuchFieldError: BANNER
	at com.Acrobot.Breeze.Utils.MaterialUtil$DataValue.name(MaterialUtil.java:450) ~[ChestShop.jar:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:195) ~[ChestShop.jar:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:152) ~[ChestShop.jar:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionLogger.onTransaction(TransactionLogger.java:29) ~[ChestShop.jar:?]
	at sun.reflect.GeneratedMethodAccessor209.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	... 23 more
```

#### What is happening?
Every time when players buy items from shop, chestshop spamly throws this error.

**Comment by Phoenix616** [comment]
You are running a really outdated server version, the current plugin version was made for 1.12.2 (and with 1.13 changes in mind).

While I try to not deliberately break support for old versions it might happen in some cases where functionality that is only in newer version needs to be accessed. The latest server version will always have priority as these are the versions that is most likely used so unfortunately there can't really be any support for four year old servers. I suggest using a build from before the last commit (or even the [release corresponding to your server version](https://dev.bukkit.org/projects/chestshop/files))

**Comment by TheDGOfficial** [comment]
Is there a build higher than build 62 working on 1.7.10? I updated from build 62, i'm going back to build 62 now. Build 62 is working on 1.7.10.

**Comment by Phoenix616** [comment]
No idea, I don't test with anything but latest. Commit 679000de153021f67c9151fe1ece709e590a8329 might actually have fixed this issue. (Although that wasn't really its purpose)
