### ISSUE TITLE
Error in start

### ISSUE THREAD

**Issue by MikhailY** [ChestShop-authors/ChestShop-3#120]
[18:49:10] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.9.1 (build 72)
[18:49:10] [Server thread/WARN]: java.sql.SQLException: Unable to run update stmt on object com.Acrobot.ChestShop.Database.Account@43da473: UPDATE `accounts` SET `name` = ?, `uuid` = ?, `lastSeen` = ? WHERE `shortName` = ?
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.stmt.mapped.MappedUpdate.update(MappedUpdate.java:129)
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.stmt.StatementExecutor.update(StatementExecutor.java:460)
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.update(BaseDaoImpl.java:352)
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:339)
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.UUIDs.NameManager.load(NameManager.java:292)
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:100)
[18:49:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:49:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[18:49:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:49:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[18:49:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[18:49:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:49:10] [Server thread/WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: accounts.name, accounts.uuid)
[18:49:10] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:909)
[18:49:10] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:921)
[18:49:10] [Server thread/WARN]: 	at org.sqlite.core.DB.execute(DB.java:825)
[18:49:10] [Server thread/WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:863)
[18:49:10] [Server thread/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99)
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.jdbc.JdbcDatabaseConnection.update(JdbcDatabaseConnection.java:263)
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.jdbc.JdbcDatabaseConnection.update(JdbcDatabaseConnection.java:191)
[18:49:10] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.stmt.mapped.MappedUpdate.update(MappedUpdate.java:101)
[18:49:10] [Server thread/WARN]: 	... 16 more

**Comment by Phoenix616** [comment]
Interesting. Please provide your config.yml and your users.db files.

**Comment by MikhailY** [comment]
i delete users.db (

**Comment by MikhailY** [comment]
http://dropmefiles.com/zcA98
