### ISSUE TITLE
NPE On Interact Event

### ISSUE THREAD

**Issue by DrOreo002** [ChestShop-authors/ChestShop-3#127]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
 ChestShop v3.9.1 (build 72)
 
#### Plugin Config
I don't think this issue will need the config.yml
 
#### Server Version
1.12.2 (Spigot)
 
#### Server Log
[13:05:33] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ChestShop v3.9.1 (build 72)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:875) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Invalid tree species for block type 2, use block type instead
	at org.bukkit.material.Wood.setSpecies(Wood.java:172) ~[Spigot.jar:git-Spigot-eadd615-bea5a84]
	at com.Acrobot.Breeze.Utils.MaterialUtil$DataValue.getData(MaterialUtil.java:397) ~[?:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getItem(MaterialUtil.java:280) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.preparePreTransactionEvent(PlayerInteract.java:162) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:124) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor493.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-eadd615-bea5a84]
	... 18 more
[13:05:33] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ChestShop v3.9.1 (build 72)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:875) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-eadd615-bea5a84]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Invalid tree species for block type 2, use block type instead
	at org.bukkit.material.Wood.setSpecies(Wood.java:172) ~[Spigot.jar:git-Spigot-eadd615-bea5a84]
	at com.Acrobot.Breeze.Utils.MaterialUtil$DataValue.getData(MaterialUtil.java:397) ~[?:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getItem(MaterialUtil.java:280) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.preparePreTransactionEvent(PlayerInteract.java:162) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:124) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor493.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-eadd615-bea5a84]
	... 18 more

#### What other plugins are you running?
Many, other plugin.

#### What is happening?
The logs explain it all

#### What did you expect to happen?
???

Please provide any additional info below
Nothing

**Comment by Phoenix616** [comment]
Are you able to you please provide some information about the shop sign that is causing this?

**Comment by DrOreo002** [comment]
Hey. I'm SOOOO sorry for not reply back here... xd. Well I stopped subscribing to this thread because the problem seems to be gone. But its back now. And I still has the same error

Btw, I don't know what sign causing this, because there's a lot of chest shop on my server.

**Comment by Phoenix616** [comment]
Make sure that you run the latest development build and if not update to it. Also please provide an updated log of the error (with the latest dev build)

If it's the same error es before it basically boils down to someone having created a shop with a wrong wood item ID. This might have already been fixed with the changes in c39720b449c6ecf73b06735e1760c15afe66e1af/build 78 though.

**Comment by DrOreo002** [comment]
I'll try it.

**Comment by DrOreo002** [comment]
Hey, sorry for the late response. It seems like the error is not available anymore. So it prob fixed, so ty for your help!. I'll mark this as closed now
