### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Rukes** [ChestShop-authors/ChestShop-3#134]
Hey, I am getting this error when server starts up

```
[03:01:59] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.8.13-SNAPSHOT (build #30)
[03:01:59] [Server thread/INFO]: [ChestShop] Updating database...
[03:01:59] [Server thread/WARN]: java.sql.SQLException: Could not run raw execute statement ALTER TABLE `accounts` RENAME TO `accounts-old`
[03:01:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[03:01:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:606)
[03:01:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Database.Migrations.migrateTo3(Migrations.java:75)
[03:01:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Database.Migrations.migrate(Migrations.java:44)
[03:01:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ChestShop.handleMigrations(ChestShop.java:182)
[03:01:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:94)
[03:01:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:01:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[03:01:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[03:01:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[03:01:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[03:01:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[03:01:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[03:01:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[03:01:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[03:01:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[03:01:59] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[03:01:59] [Server thread/WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (there is already another table or index with this name: accounts-old)
[03:01:59] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:909)
[03:01:59] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:921)
[03:01:59] [Server thread/WARN]: 	at org.sqlite.core.DB.throwex(DB.java:886)
[03:01:59] [Server thread/WARN]: 	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[03:01:59] [Server thread/WARN]: 	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
[03:01:59] [Server thread/WARN]: 	at org.sqlite.core.DB.prepare(DB.java:227)
[03:01:59] [Server thread/WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:60)
[03:01:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.jdbc.JdbcDatabaseConnection.executeStatement(JdbcDatabaseConnection.java:122)
[03:01:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.stmt.StatementExecutor.executeRawNoArgs(StatementExecutor.java:420)
[03:01:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:604)
[03:01:59] [Server thread/WARN]: 	... 15 more
[03:01:59] [Server thread/INFO]: [ChestShop] Residence version 4.7.8.2 loaded.
[03:01:59] [Server thread/INFO]: [ChestShop] Vault loaded! Found an economy plugin!
```

**Comment by Phoenix616** [comment]
You are running an outdated version. Please update to the latest development build (build 78) and check if the error persists.

**Comment by Rukes** [comment]
Okey, I'll see

**Comment by Phoenix616** [comment]
Please provide your `config.yml`, your `accounts.db` and your `version` files.

**Comment by Rukes** [comment]
[config](https://pastebin.com/83QqiFs1)
`version` file contains only `version: 2`
[users.zip](https://github.com/ChestShop-authors/ChestShop-3/files/2045572/users.zip)

**Comment by Phoenix616** [comment]
Hm, the version should be 3. Did you start converting the database to the new format and aborted it by any chance? Because your `accounts-old` table contains a lot more rows than the converted `accounts` table...

Possible quick/manual solutions would be to re-convert from a backup file (or by renaming the tables) or to just ignore the missing users (shops should work fine in most cases) and to set the version to 3. I'll also think about some more automated solutions for this case.

**Comment by Rukes** [comment]
Can I just delete users.db and set version to 3? Will shops work?

**Comment by Phoenix616** [comment]
Don't delete it (that might stop shops from working until their owners connect), just set the version to 3. If you notice lots of existing shops not working after that then you might need to go the re-convert route)

**Comment by Rukes** [comment]
Okay, I'll see.

**Comment by Rukes** [comment]
It seems fixed. For now you can close this issue. Like you said, if I notice not working shops I'll contact you.

Thanks.

(latest log)
```
[21:58:45] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.9.2-SNAPSHOT (build 78)
[21:58:46] [Server thread/INFO]: [ChestShop] Residence version 4.7.8.2 loaded.
[21:58:46] [Server thread/INFO]: [ChestShop] Vault loaded! Found an economy plugin!
[21:58:46] [Server thread/INFO]: [ChestShop] Converting numeric IDs in priceLimits.yml to Material names...
[21:58:46] [Server thread/INFO]: [ChestShop] Conversion finished!
```
