### ISSUE TITLE
named books

### ISSUE THREAD

**Issue by seema84** [ChestShop-authors/ChestShop-3#138]
if a player buy a named book and try to write in it i get this:

Couldn't handle book info
java.io.IOException: Invalid book tag!
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2229) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by Phoenix616** [comment]
Please provide some more information about how you got this book and what version of ChestShop you are running as I can't reproduce that by simply naming the book and buying it in the latest build.

**Comment by seema84** [comment]
but thats what i do.

build 79 (latest)
i rename a writable book in a anvil and buy it in a shop (without op rights and other extended rights)
do you use ProtocolLib?

**Comment by seema84** [comment]
i dont no why bot today i can't reproduce this error self
i think you can't close this issue for now

**Comment by Phoenix616** [comment]
Well the issue is definitely not with my plugin. I tested it by renaming with an anvil instead of with another plugin and it doesn't even let me write in the Book anymore, even before buying it with ChestShop so this seems to be something in the server and not this plugin.

**Comment by seema84** [comment]
"I tested it by renaming with an anvil instead of with another plugin and it doesn't even let me write in the Book anymore"

that works for me (maybe is this the problem) but thanks for your info

**Comment by seema84** [comment]
the problem was forge. with forge i can rename book and quill what this error for other player generated
