### ISSUE TITLE
Player Interact Listener Error

### ISSUE THREAD

**Issue by DrOreo002** [ChestShop-authors/ChestShop-3#139]
#### Plugin Version
ChestShop v3.9.2-SNAPSHOT (build 78)
 
#### Plugin Config
I don't think this is needed
 
#### Server Version
Spigot 1.12.2 - Latest version
 
#### Server Log
```
18.06 16:01:46 [Server] ERROR Could not pass event PlayerInteractEvent to ChestShop v3.9.2-SNAPSHOT (build 78)
18.06 16:01:46 [Server] INFO org.bukkit.event.EventException: null
18.06 16:01:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:875) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
18.06 16:01:46 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
18.06 16:01:46 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid tree species for block type 2, use block type instead
18.06 16:01:46 [Server] INFO at org.bukkit.material.Wood.setSpecies(Wood.java:172) ~[Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO at com.Acrobot.Breeze.Utils.MaterialUtil$DataValue.getData(MaterialUtil.java:395) ~[?:?]
18.06 16:01:46 [Server] INFO at com.Acrobot.Breeze.Utils.MaterialUtil.getItem(MaterialUtil.java:281) ~[?:?]
18.06 16:01:46 [Server] INFO at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.preparePreTransactionEvent(PlayerInteract.java:161) ~[?:?]
18.06 16:01:46 [Server] INFO at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:123) ~[?:?]
18.06 16:01:46 [Server] INFO at sun.reflect.GeneratedMethodAccessor504.invoke(Unknown Source) ~[?:?]
18.06 16:01:46 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
18.06 16:01:46 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
18.06 16:01:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-2086bb0-8cc5a7e]
18.06 16:01:46 [Server] INFO ... 18 more
`´`

**Comment by Phoenix616** [comment]
Same error as #127. I added compatibility for signs that might exclude the log/leaves number in 247b2d239ed83b6cac56cc3821dbe8a497f17115 and because they aren't necessary anymore removed the numbers from `/iteminfo` and the autocompletion. That also helps with the transitioning to 1.13.
