### ISSUE TITLE
1.13 Build 87 didn't run.

### ISSUE THREAD

**Issue by NullCase** [ChestShop-authors/ChestShop-3#146]
#### Plugin Version
Build 87
 
#### Plugin Config
Fresh start up, no config. 

AND Starting it with a config throws the same issue.
 
#### Server Version
Paper 1.13 version 52 (latest)
 
#### Server Log

[14:17:44] [Server thread/ERROR]: Could not load 'plugins\ChestShop.jar' in folder 'plugins'
--
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.13.jar:git-Paper-46]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.13.jar:git-Paper-46]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:320) ~[patched_1.13.jar:git-Paper-46]
at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:230) ~[patched_1.13.jar:git-Paper-46]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-46]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
in 'reader', line 327, column 104:
... e lamp, only available via state: true #Redstone Lamp
^
 
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.13.jar:git-Paper-46]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:452) ~[patched_1.13.jar:git-Paper-46]
at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:234) ~[patched_1.13.jar:git-Paper-46]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:157) ~[patched_1.13.jar:git-Paper-46]
... 5 more

#### What other plugins are you running?
Tested with and without plugins.

#### What is happening?
Doesn't run.

#### What did you expect to happen?
Run

Please provide any additional info below
Lacks enthusiasm when filling out forms.

**Comment by NullCase** [comment]
Build 88 runs.

**Comment by NullCase** [comment]
It runs and hasn't crashed. /help chestshop does list commands. But none of the commands do anything.

I tried making a couple of chestshops (1 admin shop, 1 cobblestone shop) but no response from ChestShop.

No errors in the console. It was basically like the commands & shops didn't exist.

**Comment by NullCase** [comment]
oh,  i don't have vault for 1.13 yet. That's going to explain a lot.

**Comment by NullCase** [comment]
OK its working correctly on my offline test server. Just have to figure out what about the live test server is different.

**Comment by NullCase** [comment]
28.07 17:51:59 [Server] INFO [Vault][Permission] GroupManager hooked.
28.07 17:51:59 [Server] INFO [Vault][Chat] GroupManager - Chat hooked.
28.07 17:51:59 [Server] INFO [PlaceholderAPI] Enabling PlaceholderAPI v2.9.1*
28.07 17:51:59 [Server] INFO [PlaceholderAPI] Placeholder expansion registration initializing...
28.07 17:51:59 [Server] INFO [PlaceholderAPI] Fetching available expansion information...
28.07 17:51:59 [Server] INFO [ChestShop] Enabling ChestShop v3.9.3-SNAPSHOT (build 88)
28.07 17:51:59 [Server] ERROR [ChestShop] No Economy plugin found! You need to install either Vault or Reserve and a compatible economy!

**Comment by NullCase** [comment]
Maybe you can explain this.

Running with Vault 1.6.6 (or 1.6.1) and Chestshop (build 88) results in the above "No Economy plugin found!"

BUT running with the above AND EssentialsX, EssentialsX Chat for 1.12.2, build #629 (latest) works just fine.

**Comment by Phoenix616** [comment]
Which Economy plugin did you try before EssentialsX?

**Comment by NullCase** [comment]
Vault isn't an economy plugin?

**Comment by Phoenix616** [comment]
No, Vault is an abstractions layer which simplifies the process of plugins working together. Which is why the error message says "and a compatible economy!" ;)

**Comment by NullCase** [comment]
That explains it. OK, i'll continue testing.

Great work Phoenix616
