### ISSUE TITLE
Block Physics error.

### ISSUE THREAD

**Issue by NullCase** [ChestShop-authors/ChestShop-3#147]
#### Plugin Version
Build 88
 
#### Server Version
Paper 1.13 version 52 (latest)
 
#### Server Log
```
[17:54:18] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to ChestShop v3.9.3-SNAPSHOT (build 88)
--
org.bukkit.event.EventException: null
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[patched_1.13.jar:git-Paper-52]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.jar:git-Paper-52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.jar:git-Paper-52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.13.jar:git-Paper-52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.World.a(World.java:593) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.World.applyPhysics(World.java:553) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.TileEntityChest.p(TileEntityChest.java:262) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.TileEntityChest.startOpen(TileEntityChest.java:232) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.ContainerChest.<init>(ContainerChest.java:39) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.TileEntityChest.createContainer(TileEntityChest.java:273) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.EntityPlayer.openContainer(EntityPlayer.java:834) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.BlockChest.interact(BlockChest.java:171) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.IBlockData.interact(IBlockData.java:248) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:533) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1312) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.jar:git-Paper-52]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:986) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-52]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R1.block.impl.CraftWallSign cannot be cast to org.bukkit.block.data.Rotatable
at com.Acrobot.Breeze.Utils.BlockUtil.getAttachedBlock(BlockUtil.java:55) ~[?:?]
at com.Acrobot.ChestShop.Listeners.Block.Break.SignBreak.onSign(SignBreak.java:54) ~[?:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.13.jar:git-Paper-52]
... 26 more
[17:54:19] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to ChestShop v3.9.3-SNAPSHOT (build 88)
org.bukkit.event.EventException: null
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[patched_1.13.jar:git-Paper-52]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.jar:git-Paper-52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.jar:git-Paper-52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.13.jar:git-Paper-52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.World.a(World.java:593) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.World.applyPhysics(World.java:553) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.TileEntityChest.p(TileEntityChest.java:262) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.TileEntityChest.closeContainer(TileEntityChest.java:252) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.ContainerChest.b(ContainerChest.java:101) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.EntityPlayer.m(EntityPlayer.java:997) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2046) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.jar:git-Paper-52]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:986) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-52]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-52]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R1.block.impl.CraftWallSign cannot be cast to org.bukkit.block.data.Rotatable
at com.Acrobot.Breeze.Utils.BlockUtil.getAttachedBlock(BlockUtil.java:55) ~[?:?]
at com.Acrobot.ChestShop.Listeners.Block.Break.SignBreak.onSign(SignBreak.java:54) ~[?:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.13.jar:git-Paper-52]
... 22 more
```

#### What other plugins are you running?
[List of your plugins, ideally with the version] 

#### What is happening?
Create iron ingot chestshop using autocomplete. log throws the above.

#### What did you expect to happen?
?????

Please provide any additional info below

**Comment by NullCase** [comment]
I regenerated vaults plugin.yml and retested this.

No error this time.

**Comment by NullCase** [comment]
This event triggered when right clicking a sign (opens the chest).
================

28.07 19:12:32 [Server] ERROR Could not pass event BlockPhysicsEvent to ChestShop v3.9.3-SNAPSHOT (build 88)
28.07 19:12:32 [Server] INFO org.bukkit.event.EventException: null
28.07 19:12:32 [Server] INFO at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.World.a(World.java:593) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.World.applyPhysics(World.java:554) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.TileEntityChest.p(TileEntityChest.java:262) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.TileEntityChest.closeContainer(TileEntityChest.java:252) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.ContainerChest.b(ContainerChest.java:101) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.EntityPlayer.m(EntityPlayer.java:997) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2046) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_66]
28.07 19:12:32 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_66]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:986) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
28.07 19:12:32 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R1.block.impl.CraftWallSign cannot be cast to org.bukkit.block.data.Rotatable
28.07 19:12:32 [Server] INFO at com.Acrobot.Breeze.Utils.BlockUtil.getAttachedBlock(BlockUtil.java:55) ~[?:?]
28.07 19:12:32 [Server] INFO at com.Acrobot.ChestShop.Listeners.Block.Break.SignBreak.onSign(SignBreak.java:54) ~[?:?]
28.07 19:12:32 [Server] INFO at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.13.jar:git-Paper-52]
28.07 19:12:32 [Server] INFO ... 22 more

**Comment by NullCase** [comment]
yeah, it wasn't the config.yml for vault (which would have been weird). and it wasn't creating the shop but opening the chest.

**Comment by Phoenix616** [comment]
Yeah it's a bug in the code. I'll fix it tomorrow.

**Comment by NullCase** [comment]
Testing Build 89 now.

It looks like you fixed it.

Problem has vanished. great!
