### ISSUE TITLE
NoClassDefFoundError: org/bukkit/block/data/BlockData

### ISSUE THREAD

**Issue by mibby** [ChestShop-authors/ChestShop-3#151]
ChestShop dev 89

```
[02:17:12] [Server thread/ERROR]: Error occurred while enabling ChestShop v3.9.3-SNAPSHOT (build 89) (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
	at com.Acrobot.ChestShop.ChestShop.registerPostShopCreationEvents(ChestShop.java:311) ~[?:?]
	at com.Acrobot.ChestShop.ChestShop.registerEvents(ChestShop.java:255) ~[?:?]
	at com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:106) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 14 more
[02:17:12] [Server thread/INFO]: [ChestShop] Disabling ChestShop v3.9.3-SNAPSHOT (build 89)
```

**Comment by Phoenix616** [comment]
You are trying to run as 1.13 build on an 1.12 server which will not work.
