### ISSUE TITLE
 Could not pass event TransactionEvent to ChestShop v3.9.2 (build 86)

### ISSUE THREAD

**Issue by Absolute-Garbage** [ChestShop-authors/ChestShop-3#197]
[05:20:23] [Server thread/ERROR]: Could not pass event TransactionEvent to ChestShop v3.9.2 (build 86)
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[patched_1.13.2.jar:git-Paper-510]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:132) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.13.2.jar:git-Paper-510]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:474) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-510]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-510]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{LEGACY_MELON x 1} with maximum length of 0 (code Melon results in item ItemStack{LEGACY_MELON x 1})
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:199) ~[?:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:128) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionLogger.onTransaction(TransactionLogger.java:29) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.13.2.jar:git-Paper-510]
	... 22 more
[05:20:23] [Server thread/ERROR]: Could not pass event TransactionEvent to ChestShop v3.9.2 (build 86)
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[patched_1.13.2.jar:git-Paper-510]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:132) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.13.2.jar:git-Paper-510]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:474) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-510]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-510]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-510]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{LEGACY_MELON x 1} with maximum length of 0 (code Melon results in item ItemStack{LEGACY_MELON x 1})
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:199) ~[?:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:128) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionMessageSender.parseItemInformation(TransactionMessageSender.java:90) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionMessageSender.sendMessage(TransactionMessageSender.java:81) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionMessageSender.sendBuyMessage(TransactionMessageSender.java:42) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionMessageSender.onTransaction(TransactionMessageSender.java:30) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.13.2.jar:git-Paper-510]
	... 22 more

I am unsure of why this error is popping up. I have tried new chests, different users, different locations not within worldguard regions...still the same thing pops up every time, no matter the item that I put up for sale. I will attach all logs and stuff. The thing is that the Buyer receives the item from the chest/money is deducted from balance, and the Seller gets paid. Soooo everything appears to be functional? But in case this is causing some sort of issue Im not catching right now I thought I might as well submit the error.

[config.txt](https://github.com/ChestShop-authors/ChestShop-3/files/2807841/config.txt)
[latest.log](https://github.com/ChestShop-authors/ChestShop-3/files/2807831/latest.log)
[2019-01-29-8.log.gz](https://github.com/ChestShop-authors/ChestShop-3/files/2807832/2019-01-29-8.log.gz)

**Comment by Absolute-Garbage** [comment]
Im on ChestShop v3.9.2 Byw

**Comment by Phoenix616** [comment]
You are using a 1.12 plugin version on a 1.13 server, update to the latest development build for proper 1.13 support.
