### ISSUE TITLE
iteminfo dont work ()slimefun()

### ISSUE THREAD

**Issue by brtamas0** [ChestShop-authors/ChestShop-3#219]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
[The full plugin version that you are running from /version ChestShop]
 3.10-Snapshot build 128
#### Plugin Config
Default
 
#### Server Version
git-Bukkit-a4c555b MC: 1.13.2
 
#### Server Log
Idk where is it :P 

#### What other plugins are you running?
coreprotect,sleepy,Worldedit,Groupmanager,CS-CoreLib,holodisplays,vault,griefprevention,shopkeepers,slimefun,essentials,lwc,kitadder,chestshop,chestshop,legancyIDs

#### What is happening?
Nothing. /iteminfo dont work https://imgur.com/a/mcTQNAH

#### What did you expect to happen?
/iteminfo show slimefun dust's and machines ID

**Comment by brtamas0** [comment]
16.04 18:59:19 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'iteminfo' in plugin ChestShop v3.10-SNAPSHOT (build 128)
16.04 18:59:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:138) ~[craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:682) ~[craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1587) ~[craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1447) ~[craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:37) ~[craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
16.04 18:59:19 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:843) [craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:796) [craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:699) [craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
16.04 18:59:19 [Server] INFO Caused by: java.lang.NullPointerException
16.04 18:59:19 [Server] INFO at com.Acrobot.Breeze.Utils.MaterialUtil$Metadata.getItemCode(MaterialUtil.java:419) ~[?:?]
16.04 18:59:19 [Server] INFO at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:187) ~[?:?]
16.04 18:59:19 [Server] INFO at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:143) ~[?:?]
16.04 18:59:19 [Server] INFO at com.Acrobot.ChestShop.Commands.ItemInfo.onCommand(ItemInfo.java:46) ~[?:?]
16.04 18:59:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit_1.13.2.jar:git-Bukkit-a4c555b]
16.04 18:59:19 [Server] INFO ... 15 more

**Comment by Phoenix616** [comment]
Please provide your full server log or at least the log from when the server starts up because this error should not be possible if the plugin enabled correctly.

**Comment by brtamas0** [comment]
https://pastebin.com/yQHMyDfL

**Comment by Phoenix616** [comment]
Uh, that's interesting, it failed when enabling. Apparently it's searching for SQLite's NativeDB in the wrong location? Never seen an issue like that before. Can you try updating your server and see if that fixes it? (You are 124 versions behind)

**Comment by brtamas0** [comment]
I dont know how can i updatet  my server and fix it. Can u make a short video from installing  1.13.2?

**Comment by Phoenix616** [comment]
Simply re-run [buildtools](https://www.spigotmc.org/wiki/buildtools/). It will build the server again with the latest changes.

**Comment by brtamas0** [comment]
I buyed the server, i cant re-run

**Comment by TheDGOfficial** [comment]
You are using plain Bukkit, since Bukkit (and CraftBukkit) is now already maintained by SpigotMC, switch to at least Spigot. The web panel should have an option for selecting the server software.

Some other plugins also give these errors, so it's not ChestShop's fault. Probably your server JAR file does not contain the required SQLite package.

**Comment by Phoenix616** [comment]
What's interesting is is that CraftBukkit **does** include SQLite. I also didn't see this error when testing with a plain CraftBukkit (although that might just be because some other plugin is shading in SQLite at the expected path)

And while using Spigot might be a solution it's not always possible with the changes done by it to Vanilla mechanics. (And ChestShop targets Bukkit for that reason to be compatible with all of the Bukkit-based servers so if there is a way to fix this then I would have no issue with doing so. But first he should be testing this with the latest server jar, I wont be supporting outdated versions)

**Comment by brtamas0** [comment]
apexhosting is shit. i cant update so i cant use chestshop :/ i think i need to find similar plugin or idk :(
