### ISSUE TITLE
Can't generate short name of Spawn Egg

### ISSUE THREAD

**Issue by 100petr** [ChestShop-authors/ChestShop-3#264]
#### Plugin Version
3.10-SNAPSHOT (build 152)
 
#### Plugin Config
https://hastebin.com/avelunexuv.makefile
 
#### Server Version
version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 
#### Server Log
https://hastebin.com/xugugoleya.md

#### What other plugins are you running?
PlugMan, NewItems, MultiWorld, SkinsRestorer, RankPrefixPlus, CoreProtect, WorldEdit, SoulShards, ProtocolLib, Multiverse-Core, NightVision, SimpleBossBar, PermissionsEx, CS-CoreLib, Vault, ProtocolSupport, FakaHedaMinequery, TimeVote, EpicRename, EpicHeads, LWC, WorldGuard, PermissionsExTabColors, Slimefun, EditableSign, Barrels, MyCommand, SlimeXpansion, Essentials, ExtraGear, RestrictedCreative, Jobs, QuickMarket, SlimefunGuidePlus, ActionHealth, ChestTerminal, Residence, HotbarPets, EssentialsChat, SlimefunLuckyBlocks, CommandOverride, SoulJars, ArtMap, MiniaturePets, ChestShop, SlimefunOres, ElectricSpawners, PrivateStorage, ColoredEnderChests, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, UltimateTimber, AuthMe

#### What is happening?
An error pops up when trying to determine the name.
https://hastebin.com/sugukibani.bash 

#### What did you expect to happen?
Write a name that I write on a sign

### Additional context
Nothing

**Comment by Phoenix616** [comment]
Can you provide any info on how you obtained that item?

**Comment by 100petr** [comment]
It does this with multiple animal eggs (see end of server log - silverfish). I get the egg through the itemframe, where I put it in lower version.

**Comment by Phoenix616** [comment]
Could you get me the nbt data of the item? E.g. via the data command from the itemframe or a chest or via your payer.dat when you have it in your inventory.

**Comment by 100petr** [comment]
{x: -2363, y: 4, z: 579, Items: [{Slot: 0b, id: "minecraft:pig_spawn_egg", Count: 1b, tag: {EntityTag: {id: "minecraft:pig"}}}, {Slot: 1b, id: "minecraft:ocelot_spawn_egg", Count: 1b, tag: {EntityTag: {id: "minecraft:ocelot"}}}], id: "minecraft:chest", Lock: ""}

Is that it?

**Comment by Phoenix616** [comment]
Yeah, I see, it still holds the old entity tag parameter. A bit annoying that it wouldn't remove that in the conversion process...

**Comment by Iwitrag** [comment]
Can confirm with 1.14.4 for chicken, wolf and rabbit spawn egg.

EntityTag is empty but still present.

```
java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{RABBIT_SPAWN_EGG x 5, SPAWN_EGG_META:{meta-type=SPAWN_EGG}} with maximum length of 90 (code RabbitSpawnEgg#g results in item ItemStack{RABBIT_SPAWN_EGG x 1})
at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:235) ~[?:?]
at com.Acrobot.Breeze.Utils.MaterialUtil.getSignName(MaterialUtil.java:198) ~[?:?]
at com.Acrobot.ChestShop.Listeners.PreShopCreation.ItemChecker.onPreShopCreation(ItemChecker.java:64) ~[?:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.14.4.jar:git-Paper-171]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-171]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-171]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-171]
at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:442) ~[?:?]
at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48) ~[?:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.14.4.jar:git-Paper-171]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-171]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-171]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2567) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-171]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-171]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
