### ISSUE TITLE
[1.14.4] Thrown Exception: Invalid OfflinePlayer! when creating a shop.

### ISSUE THREAD

**Issue by ZionFox** [ChestShop-authors/ChestShop-3#265]
#### Plugin Version
3.10-SNAPSHOT (build 152)
 
#### Plugin Config
```
TURN_OFF_UPDATES: false
CACHE_SIZE: 1000
SHOP_CONTAINERS: 
- "CHEST"
- "TRAPPED_CHEST"
SHOP_INTERACTION_INTERVAL: 250
IGNORE_CREATIVE_MODE: true
IGNORE_ACCESS_PERMS: true
REVERSE_BUTTONS: false
SHIFT_SELLS_IN_STACKS: false
SHIFT_ALLOWS: "ALL"
ALLOW_SIGN_CHEST_OPEN: true
ALLOW_LEFT_CLICK_DESTROYING: true
REMOVE_EMPTY_SHOPS: false
REMOVE_EMPTY_CHESTS: false
REMOVE_EMPTY_WORLDS: 
- "world1"
- "world2"
ADMIN_SHOP_NAME: "Hawkserv"
SERVER_ECONOMY_ACCOUNT: ""
TAX_AMOUNT: 0
SERVER_TAX_AMOUNT: 0
SHOP_CREATION_PRICE: 100
SHOP_REFUND_PRICE: 75
PRICE_PRECISION: 2
BLOCK_SHOPS_WITH_SELL_PRICE_HIGHER_THAN_BUY_PRICE: true
ALLOW_MULTIPLE_SHOPS_AT_ONE_BLOCK: false
ALLOW_PARTIAL_TRANSACTIONS: true
ALLOW_AUTO_ITEM_FILL: true
SHOW_MESSAGE_OUT_OF_STOCK: true
SHOW_MESSAGE_FULL_SHOP: true
NOTIFICATION_MESSAGE_COOLDOWN: 10
CSTOGGLE_TOGGLES_OUT_OF_STOCK: false
CSTOGGLE_TOGGLES_FULL_SHOP: false
SHOW_TRANSACTION_INFORMATION_CLIENT: true
SHOW_TRANSACTION_INFORMATION_OWNER: true
LOG_TO_FILE: true
LOG_TO_CONSOLE: true
LOG_ALL_SHOP_REMOVALS: true
STACK_TO_64: false
USE_BUILT_IN_PROTECTION: true
STICK_SIGNS_TO_CHESTS: false
TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY: false
TURN_OFF_SIGN_PROTECTION: false
TURN_OFF_HOPPER_PROTECTION: false
PROTECT_CHEST_WITH_LWC: true
PROTECT_SIGN_WITH_LWC: true
REMOVE_LWC_PROTECTION_AUTOMATICALLY: false
WORLDGUARD_INTEGRATION: false
WORLDGUARD_USE_FLAG: false
WORLDGUARD_USE_PROTECTION: false
AUTHME_HOOK: true
AUTHME_ALLOW_UNREGISTERED: false
HEROES_EXP: 100.0
SHOWITEM_MESSAGE: true
```
 
#### Server Version
This server is running CraftBukkit version git-Spigot-e5b1b5d-1ec1b05 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
 
#### Server Log
```
[12:31:50] [Server thread/WARN]: java.lang.IllegalArgumentException: Invalid OfflinePlayer! 38f51ae8-e8c9-4fbe-b527-c2c12c2e124a is not of server version -1
[12:31:50] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[12:31:50] [Server thread/WARN]: 	at com.Acrobot.ChestShop.UUIDs.NameManager.getOrCreateAccount(NameManager.java:59)
[12:31:50] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Listeners.PreShopCreation.NameChecker.onPreShopCreation(NameChecker.java:30)
[12:31:50] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:31:50] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:31:50] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:31:50] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:31:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[12:31:50] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:31:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[12:31:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[12:31:50] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:442)
[12:31:50] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48)
[12:31:50] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor483.invoke(Unknown Source)
[12:31:50] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:31:50] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:31:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[12:31:50] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:31:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[12:31:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2381)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3240/1236803506.run(Unknown Source)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886)
[12:31:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819)
[12:31:50] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

#### What other plugins are you running?
CoreProtect
Dynmap 3.0 Beta5
EssentialsX (& Chat/Spawn/Protect)
LWC
PermissionsEx
Vault
WorldEdit
WorldGuard

#### What is happening?
Admin shops can be created fine, however when a user attempts to make a shop, both with a filled name line, and empty name line, the sign pops off and the plugin states "Player not found!". The plugin throws an IllegalArgumentException exception, which has the stacktrace above.

#### What did you expect to happen?
The sign to stick and work as expected, populating an empty name line with the user's name.

### Additional context
Sever reports it's 7 builds out of date. I've yet to attempt to try the plugin after updating to the latest build.

**Comment by ZionFox** [comment]
To further report, this error seemed to form after just simply reloading the server plugins. It seems like something isn't correctly initialised with the plugin when this happens.

To resolve: Restart the server fully.

I know restarting the server fully is recommended when installing new plugins, but still, this issue should be looked into as it shouldn't throw an exception. It could be cleaner with the error message or exception handling to inform the user that the server needs restarting, if there's no way to pull data to make it work.
