### ISSUE TITLE
Can't make a Shop with playerheads

### ISSUE THREAD

**Issue by therealatsuga** [ChestShop-authors/ChestShop-3#284]
#### Plugin Version
3.10 - SNAPSHOT (build 137)
 
#### Plugin Config
[The full config.yml file of ChestShop]
 
#### Server Version
Paper 1.14.4 Version 230

#### Server Log
[20:00:54] [Server thread/ERROR]: Could not pass event PreShopCreationEvent to ChestShop v3.10-SNAPSHOT (build 137)
java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{PLAYER_HEAD x 1, SKULL_META:{meta-type=SKULL, internal=H4sIAAAAAAAAAE2Pt5LjVhBFsVuSanZKn6GMNTXwJIINwCHcA+E9Mng8EJbw+CZ9pDiZgpt03XO6+x1B3pG/rcdc1/qzy2GdvSE/pRT5h8rpOMKz7IOkMvqDROnkI86x/ANNiAQjYoykKeYdeX9BffacYDb+Qt6mbJvmZza+Iwjy4w35ZcGijb4nP//1sCYekq8a5wxxXUebvbpqtXA2ZmWnh3KFtL8T8WWDF1isCZBk/ekUbcy3Jzeum1bqN1phgVGzSX4SC0OdpK8eRGJxZyw4SmabCmbeo3oHHQI3LzgDavZS6a50H9pR7+QDXCNZTwPccONHBSLBmnPslLVXX1AH4XD5TQp1apMNnjFFLyNOJHomp8+rJ2QUDSw+HmXy1Jsb0KrZNqe9I3xLoS8PdD9bm+bKOtXzCmktkF7aOVnDBaxb1FEPnYbFIRMrSx4orTaocDw8j3FD1lo5S8sxSqHi2SlZJluB5y/JjTFuY3/KqiuPD7SMqly/bPXQyDvV8K6In3rQH3vZfyqr72QULhUnnHpWFjNyQJZUZn3qUgq082MmIp0wKpfJShlAos2HKOtFCRPVIw2ZKrjk8GF33SVdNzidF008n++mlxTyhMorqV1De5qGh9w/z/o19bZBtZPdfcQjfLiC8IT2btgWRt7yM9HW94SnqXrx8AuW0nnr9TbTOZUxTFk3cVjDU53N8a7NZc7Acxl7KjjWQNd5Q71MKiiDTFrafHZJdqKqQTg9LTMivTX55AH7CPaQxsZcXaMT2iuhB8LaMVYDR2NJzHT3kxYl0N5Tbh3MsZRZXu9y+xAsvHC4+CgDv7bHI1iq4ap8XgZNAcNm5LiAwV0oFp1ZOk6fU/yaSqERKGSMSTZ7DMrvN+RPN6rn7Ied7QCNPKxOCLOMfRZqFYepR4BrtrOqh7ErN2OU2use42EfCy4IvyRaqtxGbUCpNG6t3l6pjFVtVBhWfKMIyhEc3BFUHKpWDiXBFSYiWMKmHkOHKmPPgRoEZSqqWIhz8P4FjshL58A3saRxrdDnscgH9feeVARYaK0wFVwyFd099BWotSN00AnYUKJft7+Y9dvXpaK5avCy/K87x149h566B16I3huqTr8YNPRLNH357ziHK7hZaXZZqTe1DCtnDasEU24K+vphV28OEVZXqNzKUvPcSvEkTLXTOsDDKsAdQrENNKwKTLOLF+OW2o09lC/A5D76G0HekD/UqMmQv6JpnIsIQf4DxRNnzIUEAAA=, skull-owner=atsuga}} with maximum length of 90 (code Player Head#I results in item ItemStack{PLAYER_HEAD x 1, SKULL_META:{meta-type=SKULL, internal=H4sIAAAAAAAAAE2Pt5LjVhBFsVuSanZKn6GMNTXwJIINwCHcA+E9Mng8EJbw+CZ9pDiZgpt03XO6+x1B3pG/rcdc1/qzy2GdvSE/pRT5h8rpOMKz7IOkMvqDROnkI86x/ANNiAQjYoykKeYdeX9BffacYDb+Qt6mbJvmZza+Iwjy4w35ZcGijb4nP//1sCYekq8a5wxxXUebvbpqtXA2ZmWnh3KFtL8T8WWDF1isCZBk/ekUbcy3Jzeum1bqN1phgVGzSX4SC0OdpK8eRGJxZyw4SmabCmbeo3oHHQI3LzgDavZS6a50H9pR7+QDXCNZTwPccONHBSLBmnPslLVXX1AH4XD5TQp1apMNnjFFLyNOJHomp8+rJ2QUDSw+HmXy1Jsb0KrZNqe9I3xLoS8PdD9bm+bKOtXzCmktkF7aOVnDBaxb1FEPnYbFIRMrSx4orTaocDw8j3FD1lo5S8sxSqHi2SlZJluB5y/JjTFuY3/KqiuPD7SMqly/bPXQyDvV8K6In3rQH3vZfyqr72QULhUnnHpWFjNyQJZUZn3qUgq082MmIp0wKpfJShlAos2HKOtFCRPVIw2ZKrjk8GF33SVdNzidF008n++mlxTyhMorqV1De5qGh9w/z/o19bZBtZPdfcQjfLiC8IT2btgWRt7yM9HW94SnqXrx8AuW0nnr9TbTOZUxTFk3cVjDU53N8a7NZc7Acxl7KjjWQNd5Q71MKiiDTFrafHZJdqKqQTg9LTMivTX55AH7CPaQxsZcXaMT2iuhB8LaMVYDR2NJzHT3kxYl0N5Tbh3MsZRZXu9y+xAsvHC4+CgDv7bHI1iq4ap8XgZNAcNm5LiAwV0oFp1ZOk6fU/yaSqERKGSMSTZ7DMrvN+RPN6rn7Ied7QCNPKxOCLOMfRZqFYepR4BrtrOqh7ErN2OU2use42EfCy4IvyRaqtxGbUCpNG6t3l6pjFVtVBhWfKMIyhEc3BFUHKpWDiXBFSYiWMKmHkOHKmPPgRoEZSqqWIhz8P4FjshL58A3saRxrdDnscgH9feeVARYaK0wFVwyFd099BWotSN00AnYUKJft7+Y9dvXpaK5avCy/K87x149h566B16I3huqTr8YNPRLNH357ziHK7hZaXZZqTe1DCtnDasEU24K+vphV28OEVZXqNzKUvPcSvEkTLXTOsDDKsAdQrENNKwKTLOLF+OW2o09lC/A5D76G0HekD/UqMmQv6JpnIsIQf4DxRNnzIUEAAA=, skull-owner=atsuga}})
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:203) ~[?:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getSignName(MaterialUtil.java:166) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PreShopCreation.ItemChecker.onPreShopCreation(ItemChecker.java:64) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.14.4.jar:git-Paper-236]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-236]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-236]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-236]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:440) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:35) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.14.4.jar:git-Paper-236]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-236]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-236]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2571) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-236]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
 

#### What other plugins are you running?

AdvancedClans
 AntiWorldFly 
bStats  
 BuycraftX 
ChestShop 
 ChestShopNotifier 
CMI 
ColoredAnvils 
 Confiscate 
CosmeticsTreasure 
EliteLootbox 
IllegalStack  
ItemSignature 
Jobs 
LagAssist 
LiteBans 
LuckPerms 
MCPerks 
MineSecure 
Modifyworld 
Multiverse-Core 
 MVdWPlugin 
MyCommand  
 NoVPN 
Parkour  
PlaceholderAPI 
PlayerReport  
PlotSquared 
PluginHiderPlus  
PluginMetrics 
PlugMan  
ProtocolLib 
SelectionVisualizer 
 Spartan 
SpigotUpdates  
TAB 
TradeMe  
TreysCommandBlocker 
Vault  
ViaVersion 
Votifier  
Winter  
 WorldEdit 
WorldGuard

#### What is happening?
I can't create a shop with heads. Doesn't matter if I click the sign with a head in hand or if I store the item in the chest to create it. It just throws the error above into console

#### What did you expect to happen?
A shop should be created

**Comment by Phoenix616** [comment]
You are running an outdated version of the plugin, please update to the latest one and see if the issue persists.

**Comment by therealatsuga** [comment]
Ok, I'll do so and report if it does persist. Thank you
