### ISSUE TITLE
Not work with CMI

### ISSUE THREAD

**Issue by Temale62** [ChestShop-authors/ChestShop-3#298]
#### Plugin Version
>.... [23:34:50 INFO]: ChestShop version 3.10.2-SNAPSHOT (build 176)
 
#### Plugin Config
https://pastebin.com/U3huxPk7
 
#### Server Version
Paper-155 version 1.15.2
 
#### Server Log

>.... [23:31:12 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'chestshop' in plugin ChestShop v3.10 (build 165) - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.15.2.jar:git-Paper-90]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-90]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-90]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

#### What other plugins are you running?
Admin-Chat-Channel*, AutoMessage*, BetterBrushes*, BKCommonLib, BlockLocker, ChestShop, ChestShopNotifier*, Citizens, CMI, ColoredTablist*, DeathMessagesPrime, EXPBank-6.0.0, FastAsyncWorldEdit*, HolographicDisplays, Jobs, LibsDisguises, LogBlock, LuckPerms, Multiverse-Core*, Multiverse-Inventories*, MyCommand, MyPet, OnTime*, PhantomX, PlotSquared, ProtocolLib, Quests, Residence, ServerListPlus*, Shell*, Shopkeepers, Skript, SuperVanish, TNTRun*, Vault, ViaVersion*, VoteNotif*, VoxelSniper*, WolfyUtilities, WorldEdit, WorldGuard

#### What is happening?
apparently ChestShop does not recognize CMI as an economy plugin

#### What did you expect to happen?
If possible an update to resolve the issue, or tell me how to connect the two plugins

thank you in advance

**Comment by Phoenix616** [comment]
The plugin is disabled. Please provide your startup log, it should show why it is disabled.

**Comment by Temale62** [comment]
I summarized in there
https://pastebin.com/24vL1rNZ

**Comment by Phoenix616** [comment]
Please provide the full startup log, not just some small part you think might be useful because you are missing the information where ChestShop actually gets disabled.

**Comment by Temale62** [comment]
https://pastebin.com/uzN6gLg6

**Comment by Phoenix616** [comment]
You do not have Vault installed. That is required for the plugin to work with your economy plugin.

**Comment by Temale62** [comment]
sorry it was bad latest
https://pastebin.com/PigGHu9i

**Comment by Phoenix616** [comment]
> `[03:28:03] [Server thread/ERROR]: [ChestShop] No Vault compatible Economy plugin found!`

You are missing an economy plugin, you'll need to install one which works properly for the plugin to work. CMI even tells you that it will not provide an economy (on line 945) in the log so that's an issue with them.

**Comment by Temale62** [comment]
CMI has an economy but is not recognized in the plugin Vault

ChestShop only works with Vault, impossible to connect it directly to CMI ?

**Comment by Phoenix616** [comment]
I suggest contacting their support, non of your Vault-depending pcugins are pickup up on the CMI economy. I would be very surprised if it didn't support Vault seeing as 99.9% of plugins use Vault's adapters.
