### ISSUE TITLE
Player can´t open a shop

### ISSUE THREAD

**Issue by Dartume** [ChestShop-authors/ChestShop-3#382]
Hello,

we have an issue regarding the creation of ingame chest shops for PE players connecting over Geyser (with floodgate).

 

Config:

[09:07:27] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.11.1-SNAPSHOT (build 249)
[09:07:27] [Server thread/INFO]: [ChestShop] Loading configuration config.yml
[09:07:27] [Server thread/INFO]: [ChestShop] DEBUG: true
[09:07:27] [Server thread/INFO]: [ChestShop] TURN_OFF_UPDATES: true
[09:07:27] [Server thread/INFO]: [ChestShop] TURN_OFF_DEV_UPDATE_NOTIFIER: false
[09:07:27] [Server thread/INFO]: [ChestShop] INCLUDE_SETTINGS_IN_METRICS: true
[09:07:27] [Server thread/INFO]: [ChestShop] CACHE_SIZE: 1000
[09:07:27] [Server thread/INFO]: [ChestShop] DEFAULT_LANGUAGE: "de"
[09:07:27] [Server thread/INFO]: [ChestShop] USE_CLIENT_LOCALE: false
[09:07:27] [Server thread/INFO]: [ChestShop] SHOP_CONTAINERS:
- "CHEST"
- "TRAPPED_CHEST"
[09:07:27] [Server thread/INFO]: [ChestShop] SHOP_INTERACTION_INTERVAL: 250
[09:07:27] [Server thread/INFO]: [ChestShop] IGNORE_CREATIVE_MODE: true
[09:07:27] [Server thread/INFO]: [ChestShop] IGNORE_ACCESS_PERMS: false
[09:07:27] [Server thread/INFO]: [ChestShop] REVERSE_BUTTONS: false
[09:07:27] [Server thread/INFO]: [ChestShop] SHIFT_SELLS_IN_STACKS: true
[09:07:27] [Server thread/INFO]: [ChestShop] SHIFT_SELLS_EVERYTHING: false
[09:07:27] [Server thread/INFO]: [ChestShop] SHIFT_ALLOWS: "ALL"
[09:07:27] [Server thread/INFO]: [ChestShop] ALLOW_SIGN_CHEST_OPEN: false
[09:07:27] [Server thread/INFO]: [ChestShop] ALLOW_LEFT_CLICK_DESTROYING: true
[09:07:27] [Server thread/INFO]: [ChestShop] REMOVE_EMPTY_SHOPS: false
[09:07:27] [Server thread/INFO]: [ChestShop] REMOVE_EMPTY_CHESTS: false
[09:07:27] [Server thread/INFO]: [ChestShop] REMOVE_EMPTY_WORLDS:
- "world1"
- "world2"
[09:07:27] [Server thread/INFO]: [ChestShop] ADMIN_SHOP_NAME: "Admin Shop"
[09:07:27] [Server thread/INFO]: [ChestShop] SERVER_ECONOMY_ACCOUNT: ""
[09:07:27] [Server thread/INFO]: [ChestShop] SERVER_ECONOMY_ACCOUNT_UUID: 00000000-0000-0000-0000-000000000000
[09:07:27] [Server thread/INFO]: [ChestShop] TAX_AMOUNT: 0
[09:07:27] [Server thread/INFO]: [ChestShop] SERVER_TAX_AMOUNT: 0
[09:07:27] [Server thread/INFO]: [ChestShop] SHOP_CREATION_PRICE: 0
[09:07:27] [Server thread/INFO]: [ChestShop] SHOP_REFUND_PRICE: 0
[09:07:27] [Server thread/INFO]: [ChestShop] PRICE_PRECISION: 2
[09:07:27] [Server thread/INFO]: [ChestShop] BLOCK_SHOPS_WITH_SELL_PRICE_HIGHER_THAN_BUY_PRICE: true
[09:07:27] [Server thread/INFO]: [ChestShop] MAX_SHOP_AMOUNT: 3456
[09:07:27] [Server thread/INFO]: [ChestShop] ALLOW_MULTIPLE_SHOPS_AT_ONE_BLOCK: false
[09:07:27] [Server thread/INFO]: [ChestShop] ALLOW_PARTIAL_TRANSACTIONS: true
[09:07:27] [Server thread/INFO]: [ChestShop] ALLOW_AUTO_ITEM_FILL: true
[09:07:27] [Server thread/INFO]: [ChestShop] BUNGEECORD_MESSAGES: true
[09:07:27] [Server thread/INFO]: [ChestShop] SHOW_MESSAGE_OUT_OF_STOCK: true
[09:07:27] [Server thread/INFO]: [ChestShop] SHOW_MESSAGE_FULL_SHOP: true
[09:07:27] [Server thread/INFO]: [ChestShop] NOTIFICATION_MESSAGE_COOLDOWN: 10
[09:07:27] [Server thread/INFO]: [ChestShop] CSTOGGLE_TOGGLES_OUT_OF_STOCK: false
[09:07:27] [Server thread/INFO]: [ChestShop] CSTOGGLE_TOGGLES_FULL_SHOP: false
[09:07:27] [Server thread/INFO]: [ChestShop] SHOW_TRANSACTION_INFORMATION_CLIENT: true
[09:07:27] [Server thread/INFO]: [ChestShop] SHOW_TRANSACTION_INFORMATION_OWNER: true
[09:07:27] [Server thread/INFO]: [ChestShop] LOG_TO_FILE: false
[09:07:27] [Server thread/INFO]: [ChestShop] LOG_TO_CONSOLE: true
[09:07:27] [Server thread/INFO]: [ChestShop] LOG_ALL_SHOP_REMOVALS: true
[09:07:27] [Server thread/INFO]: [ChestShop] STACK_TO_64: false
[09:07:27] [Server thread/INFO]: [ChestShop] USE_BUILT_IN_PROTECTION: true
[09:07:27] [Server thread/INFO]: [ChestShop] STICK_SIGNS_TO_CHESTS: false
[09:07:27] [Server thread/INFO]: [ChestShop] TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY: false
[09:07:27] [Server thread/INFO]: [ChestShop] TURN_OFF_SIGN_PROTECTION: false
[09:07:27] [Server thread/INFO]: [ChestShop] TURN_OFF_HOPPER_PROTECTION: false
[09:07:27] [Server thread/INFO]: [ChestShop] CHECK_ACCESS_FOR_SHOP_USE: false
[09:07:27] [Server thread/INFO]: [ChestShop] PROTECT_CHEST_WITH_LWC: false
[09:07:27] [Server thread/INFO]: [ChestShop] LWC_CHEST_PROTECTION_TYPE: "PRIVATE"
[09:07:27] [Server thread/INFO]: [ChestShop] PROTECT_SIGN_WITH_LWC: false
[09:07:27] [Server thread/INFO]: [ChestShop] LWC_SIGN_PROTECTION_TYPE: "PRIVATE"
[09:07:27] [Server thread/INFO]: [ChestShop] REMOVE_LWC_PROTECTION_AUTOMATICALLY: true
[09:07:27] [Server thread/INFO]: [ChestShop] LWC_LIMITS_BLOCK_CREATION: true
[09:07:27] [Server thread/INFO]: [ChestShop] WORLDGUARD_INTEGRATION: false
[09:07:27] [Server thread/INFO]: [ChestShop] WORLDGUARD_USE_FLAG: false
[09:07:27] [Server thread/INFO]: [ChestShop] WORLDGUARD_USE_PROTECTION: false
[09:07:27] [Server thread/INFO]: [ChestShop] GRIEFPREVENTION_INTEGRATION: false
[09:07:27] [Server thread/INFO]: [ChestShop] REDPROTECT_INTEGRATION: false
[09:07:27] [Server thread/INFO]: [ChestShop] AUTHME_HOOK: false
[09:07:27] [Server thread/INFO]: [ChestShop] AUTHME_ALLOW_UNREGISTERED: true
[09:07:27] [Server thread/INFO]: [ChestShop] HEROES_EXP: 100.0
[09:07:27] [Server thread/INFO]: [ChestShop] SHOWITEM_MESSAGE: true
[09:07:27] [Server thread/INFO]: [ChestShop] USE_STOCK_COUNTER: false
[09:07:27] [Server thread/INFO]: [ChestShop] Found locale cs!
[09:07:27] [Server thread/INFO]: [ChestShop] Found locale de!
[09:07:27] [Server thread/INFO]: [ChestShop] Found locale en!
[09:07:27] [Server thread/INFO]: [ChestShop] Found legacy local.yml. Loading it as 'legacy' language and using that for all messages.
[09:07:27] [Server thread/INFO]: [ChestShop] As long as the legacy file is used automatic language switching based on the client settings will not be supported!
[09:07:27] [Server thread/INFO]: [ChestShop] Import it into the corresponding language file and remove/rename the file if you don't want it anymore!
[09:07:27] [Server thread/WARN]: [ChestShop] No default config 'local.yml' found in ChestShop's jar file!
[09:07:27] [Server thread/INFO]: [ChestShop] Using Essentials Economy as the Economy provider now.
[09:07:27] [Server thread/INFO]: [ChestShop] Vault loaded!
[09:07:27] [Server thread/INFO]: [ChestShop] Using Paper's BlockDestroyEvent instead of the BlockPhysicsEvent!
[09:07:27] [Server thread/INFO]: [ChestShop] Auto-updater is disabled. If you want the plugin to automatically download new releases then set 'TURN_OFF_UPDATES' to 'false' in your config.yml!

 

Error:

[09:28:23] [Server thread/WARN]: java.lang.IllegalArgumentException: Invalid OfflinePlayer! 00000000-0000-0000-0009-000007475b72 is not of server version 4
[09:28:23] [Server thread/WARN]: at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[09:28:23] [Server thread/WARN]: at com.Acrobot.ChestShop.UUIDs.NameManager.getOrCreateAccount(NameManager.java:82)
[09:28:23] [Server thread/WARN]: at com.Acrobot.ChestShop.UUIDs.NameManager.getOrCreateAccount(NameManager.java:68)
[09:28:23] [Server thread/WARN]: at com.Acrobot.ChestShop.Listeners.PreShopCreation.NameChecker.handleEvent(NameChecker.java:41)
[09:28:23] [Server thread/WARN]: at com.Acrobot.ChestShop.Listeners.PreShopCreation.NameChecker.onPreShopCreation(NameChecker.java:24)
[09:28:23] [Server thread/WARN]: at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[09:28:23] [Server thread/WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[09:28:23] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:28:23] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[09:28:23] [Server thread/WARN]: at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:523)
[09:28:23] [Server thread/WARN]: at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48)
[09:28:23] [Server thread/WARN]: at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[09:28:23] [Server thread/WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[09:28:23] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:28:23] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2792)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$15(PlayerConnection.java:2745)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:321)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:335)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004)
[09:28:23] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[09:28:23] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by Phoenix616** [comment]
The UUID of a player needs to match tour server's online mode setting for the plugin to be able to work correctly. Please enable the option in geyser/floodgate which gives each Bedrock player the appropriate real UUID (if such an option exists, if not I suggest requesting one)

**Comment by Dartume** [comment]
Bedrock player don´t have a real UUID the UUID in the log is a generate UUID from geyser and with this other plugins (plotsquard) work only Chest shop say i don´t work with this Offline UUID

**Comment by Phoenix616** [comment]
They should be able to grant real UUIDs or at least link real accounts so that compatible UUIDs are used. Using any version of UUID that does not match the server's online mode could lead to issues with ChestShop and lots of other plugins using the Vault API's economy adapter and having to check the UUID version to not create errors on transactions.

**Comment by Dartume** [comment]
The PE Player can buy and sell normaly the economy works only the creation of an own shop sign don´t go

**Comment by Phoenix616** [comment]
The issue happens when the shop's owner is offline and money is transferred to their account, not for the player using the shop.

**Comment by Dartume** [comment]
the issue is wenn the PE Player in this ticket the user with the UUID 00000000-0000-0000-0009-000007475b72 will create a shop sign the system say the player name can´t be found he is online and will aktiv create the sign.

**Comment by Phoenix616** [comment]
The check can now by disabled with the new `ENSURE_CORRECT_PLAYERID` config option. Doing so can lead to issues for sales with offline shop owners so disabling that check is not supported and any issue should be tested by enabling the option first.
