### ISSUE TITLE
Iteminfo gives an error

### ISSUE THREAD

**Issue by x1p** [ChestShop-authors/ChestShop-3#395]
#### Plugin Version

 ChestShop build 263
 
#### Plugin Config

<details>
  <summary>Config</summary>
  
 ```yaml
 [Put the config here]
 ```
 
 </details>
 
#### Server Version

 1.16.3
 
#### Server Log

<details>
  <summary>Log</summary>
No error on the console/log file
The only clue is in ChestShop.log:

```
2021/01/04 19:11:19 Error while generating shop sign item name
```

</details>

#### What other plugins are you running?

WE 7.2.1. WG 7.0.4

#### What is happening?

Iteminfo gives me this error:
Me doing: /iteminfo with an enchanted book in my hand
Full Name: Enchanted Book#3X
![Screenshot192459](https://user-images.githubusercontent.com/28690790/103567410-105cb600-4ec4-11eb-89a9-0f40175d8ec6.png)

The Shop Sign is missing in this message

#### What did you expect to happen?

Work as usual to give me the shop sign name.
Other books work fine. Only this book not. It's the thorn 3 enchantment, but that is prob irrelevant because it works on a test server.

**Comment by Phoenix616** [comment]
Please provide the gull server log as well as your config.

**Comment by x1p** [comment]
[latest.log](https://github.com/ChestShop-authors/ChestShop-3/files/5766820/latest.log)

[config.yml.txt](https://github.com/ChestShop-authors/ChestShop-3/files/5766827/config.yml.txt)

**Comment by Phoenix616** [comment]
Please enable `LOG_TO_CONSOLE` and try again, apparently the external file logger does not include the full error message.

**Comment by x1p** [comment]
After `/chestshop reload`, it does not output any more than we know now. So I have to await a restart by night.

**Comment by x1p** [comment]
Ok, I made a shop with this particular book.
```
[23:27:38 ERROR]: Could not pass event PreShopCreationEvent to ChestShop v3.11.1-SNAPSHOT (build 263)
java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{ENCHANTED_BOOK x 1, ENCHANTED_META:{meta-type=ENCHANTED, stored-enchants={SOUL_SPEED=3}}} with maximum length of 90 (code EnchanteBook#3x results in item ItemStack{ENCHANTED_BOOK x 1, ENCHANTED_META:{meta-type=ENCHANTED, enchants={DURABILITY=1}}})
at com.Acrobot.ChestShop.Utils.ItemUtil.getName(ItemUtil.java:82) ~[?:?]
at com.Acrobot.ChestShop.Utils.ItemUtil.getSignName(ItemUtil.java:97) ~[?:?]
at com.Acrobot.ChestShop.Listeners.PreShopCreation.ItemChecker.onPreShopCreation(ItemChecker.java:63) ~[?:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.3.jar:git-Purpur-808]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Purpur-808]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Purpur-808]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Purpur-808]
at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:540) ~[?:?]
at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48) ~[?:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.3.jar:git-Purpur-808]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Purpur-808]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Purpur-808]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2763) ~[?:git-Purpur-808]
at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:41) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:9) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1203) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1196) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1333) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.3.jar:git-Purpur-808]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Purpur-808]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Phoenix616** [comment]
Well this says that it somehow created the wrong code or got the wrong item from the code. This might have multiple reasons, either an error in the recent changes or how the server itself serialises items (seeing as you don't use Spigot/Paper that might be possible).

Can you provider your items.db file as well as test if this issue occurs on ChestShop build 260 too (and maybe even Spigot/Paper if you can but I realise that that might not be possible if that only occurs on production)

**Comment by x1p** [comment]
Build 260 works fine.

[items.zip](https://github.com/ChestShop-authors/ChestShop-3/files/5767895/items.zip)

**Comment by andris155** [comment]
Same problem.
```
[23:13:14] [Server thread/ERROR]: Could not pass event PreShopCreationEvent to ChestShop v3.11.1-SNAPSHOT (build 263)
java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{DAYLIGHT_DETECTOR x 1, TILE_ENTITY_META:{meta-type=TILE_ENTITY, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Carbonado Solar Generator"}],"text":""}, lore=[{"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"End-Game Generator"}],"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"⇨ "},{"italic":false,"color":"yellow","text":"⚡ "},{"italic":false,"color":"gray","text":"0 J Buffer"}],"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"⇨ "},{"italic":false,"color":"yellow","text":"⚡ "},{"italic":false,"color":"gray","text":"64 J/s"}],"text":""}], PublicBukkitValues={slimefun:slimefun_item=SOLAR_GENERATOR_3}, blockMaterial=DAYLIGHT_DETECTOR}} with maximum length of 90 (code DaylightDetector# results in item ItemStack{DAYLIGHT_DETECTOR x 1})
	at com.Acrobot.ChestShop.Utils.ItemUtil.getName(ItemUtil.java:82) ~[?:?]
	at com.Acrobot.ChestShop.Utils.ItemUtil.getSignName(ItemUtil.java:97) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PreShopCreation.ItemChecker.onPreShopCreation(ItemChecker.java:63) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:540) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2846) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$18(PlayerConnection.java:2791) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:340) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:354) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:114) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1200) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1193) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:125) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1169) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1013) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

```
[19:07:41] [Server thread/ERROR]: Could not pass event PreShopCreationEvent to ChestShop v3.11.1-SNAPSHOT (build 263)
java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{RED_TERRACOTTA x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Electric Ingot Factory "},{"italic":false,"color":"gray","text":"("},{"italic":false,"color":"yellow","text":"III"},{"italic":false,"color":"gray","text":")"}],"text":""}, lore=[{"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"End-Game Machine"}],"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"⇨ "},{"italic":false,"color":"aqua","text":"⚡ "},{"italic":false,"color":"gray","text":"Speed: "},{"italic":false,"color":"aqua","text":"8.0x"}],"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"⇨ "},{"italic":false,"color":"yellow","text":"⚡ "},{"italic":false,"color":"gray","text":"40 J/s"}],"text":""}], PublicBukkitValues={slimefun:slimefun_item=ELECTRIC_INGOT_FACTORY_3}}} with maximum length of 90 (code RedTerracotta#v results in item ItemStack{RED_TERRACOTTA x 1})
	at com.Acrobot.ChestShop.Utils.ItemUtil.getName(ItemUtil.java:82) ~[?:?]
	at com.Acrobot.ChestShop.Utils.ItemUtil.getSignName(ItemUtil.java:97) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PreShopCreation.ItemChecker.onPreShopCreation(ItemChecker.java:63) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:540) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2846) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$18(PlayerConnection.java:2791) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:340) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:354) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:114) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1200) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1193) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:125) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1169) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1013) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Yatopia-"63ce6fb"]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by andris155** [comment]
[items.zip](https://github.com/ChestShop-authors/ChestShop-3/files/5772900/items.zip)
