### ISSUE TITLE
Problem number of id object enchanted

### ISSUE THREAD

**Issue by thedourn** [ChestShop-authors/ChestShop-3#397]
#### Plugin Version
ChestShop#264
 

#### Server Version
Paper 1.16.3#192
 
 
#### Server Log

<details>
  <summary>Log</summary>

[17:26:37] [Server thread/ERROR]: Could not pass event PreShopCreationEvent to ChestShop v3.11.1-SNAPSHOT (build 264)
java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{ENCHANTED_BOOK x 1, ENCHANTED_META:{meta-type=ENCHANTED, stored-enchants={LOYALTY=3}}} with maximum length of 90 (code EnchantedBook#m results in item ItemStack{ENCHANTED_BOOK x 1, ENCHANTED_META:{meta-type=ENCHANTED, stored-enchants={ARROW_KNOCKBACK=2}}})
	at com.Acrobot.ChestShop.Utils.ItemUtil.getName(ItemUtil.java:82) ~[?:?]
	at com.Acrobot.ChestShop.Utils.ItemUtil.getSignName(ItemUtil.java:97) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PreShopCreation.ItemChecker.onPreShopCreation(ItemChecker.java:63) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.3.jar:git-Paper-192]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-192]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-192]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-192]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:540) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.3.jar:git-Paper-192]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-192]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-192]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2686) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:41) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:9) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-192]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

</details>

#### What is happening?
I arrived at the maximum number of id generation for the plugin if I understood well.

#### What did you expect to happen?
Is there a way to increase the number of id max without deleting the old ones?

Thank

Thedourn

**Comment by Phoenix616** [comment]
You are using an old build, that issue (#395) is already fixed.
