### ISSUE TITLE
Unable to shorten too long item aliases

### ISSUE THREAD

**Issue by Leahcimkrob** [ChestShop-authors/ChestShop-3#425]
#### Plugin Version
ChestShop Dev Build 283
 
 
#### Plugin Config
ItemAlias.yml:
Spruce Planks: Fichtenholzbretter
 
#### Server Version
1.16.2
 
 
#### Server Log
[08:04:14] [Server thread/ERROR]: [ChestShop] Error while generating shop sign item name
java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{SPRUCE_PLANKS x 1} with maximum length of 90 (code Fichtenholzbrette results in item null)
at com.Acrobot.ChestShop.Utils.ItemUtil.getName(ItemUtil.java:82) ~[?:?]
at com.Acrobot.ChestShop.Utils.ItemUtil.getSignName(ItemUtil.java:97) ~[?:?]
at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:100) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor91.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:465) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1284) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
at java.lang.Thread.run(Thread.java:834) [?:?]

#### What is happening?
Shop with Spruce Planks can't create

**Comment by Leahcimkrob** [comment]
I use now Build 285, but I have the same Error wirth an other Item:

[05:49:27] [Server thread/ERROR]: Could not pass event PreShopCreationEvent to ChestShop v3.12-SNAPSHOT (build 285)
java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{VILLAGER_SPAWN_EGG x 1} with maximum length of 90 (code Dorfbewohner-sp results in item null)
at com.Acrobot.ChestShop.Utils.ItemUtil.getName(ItemUtil.java:82) ~[?:?]
at com.Acrobot.ChestShop.Utils.ItemUtil.getSignName(ItemUtil.java:97) ~[?:?]
at com.Acrobot.ChestShop.Listeners.PreShopCreation.ItemChecker.onPreShopCreation(ItemChecker.java:63) ~[?:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.2.jar:git-Paper-186]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-186]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-186]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-186]
at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:544) ~[?:?]
at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48) ~[?:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.2.jar:git-Paper-186]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-186]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-186]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2686) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:41) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:9) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-186]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Leahcimkrob** [comment]
The longest Alias is: Cracked Polished Blackstone Bricks: Rissige polierte Schwarzsteinziegel
This Item are not buyable.
No more errormessage.

**Comment by Phoenix616** [comment]
Both work for me without issues, please provide your complete itemAliases.yml file as well as your full log file.

**Comment by Leahcimkrob** [comment]
Here are our files

[itemAliases and Log.zip](https://github.com/ChestShop-authors/ChestShop-3/files/6216295/itemAliases.and.Log.zip)
