### ISSUE TITLE
Im getting the following errror when i some trys to create a shot

### ISSUE THREAD

**Issue by TaminoPalm** [ChestShop-authors/ChestShop-3#434]
#### Plugin Version

 
 Newest version
#### Plugin Config

<details>
  <summary>Config</summary>
  
 ```yaml
 [Put the config here]
 ```
 
 </details>
 
#### Server Version

 
 Tuinity newest version
#### Server Log

<details>
  <summary>Log</summary>
[11:48:45] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.UUIDs.NameManager.getOrCreateAccount(NameManager.java:82)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.UUIDs.NameManager.getOrCreateAccount(NameManager.java:68)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Listeners.PreShopCreation.NameChecker.handleEvent(NameChecker.java:41)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Listeners.PreShopCreation.NameChecker.onPreShopCreation(NameChecker.java:24)
[11:48:45] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[11:48:45] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[11:48:45] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:48:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:518)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48)
[11:48:45] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[11:48:45] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[11:48:45] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:48:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:3026)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$18(PlayerConnection.java:2983)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:473)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:487)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1311)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1304)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1379)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[11:48:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[11:48:45] [Server thread/WARN]: java.lang.IllegalArgumentException: Invalid OfflinePlayer! 6330fc2d-1ba7-4ea0-bd7c-bfa8064715be is not of server version 0
[11:48:45] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.UUIDs.NameManager.getOrCreateAccount(NameManager.java:82)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.UUIDs.NameManager.getOrCreateAccount(NameManager.java:68)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Listeners.PreShopCreation.NameChecker.handleEvent(NameChecker.java:41)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Listeners.PreShopCreation.NameChecker.onPreShopCreationHighest(NameChecker.java:29)
[11:48:45] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[11:48:45] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[11:48:45] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:48:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:518)
[11:48:45] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:48)
[11:48:45] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[11:48:45] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[11:48:45] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:48:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:3026)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$18(PlayerConnection.java:2983)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:473)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:487)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1311)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1304)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1379)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120)
[11:48:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[11:48:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
[Your log here]
```

</details>

#### What is happening?

The Player gets the message player not found on shop creation

**Comment by Phoenix616** [comment]
"Newest“ or "Latest" are not versions, please provide your exact version as well as the full log. (You cut off parts of it)
