### ISSUE TITLE
Error ChestShop.Metrics

### ISSUE THREAD

**Issue by Naghtrion** [ChestShop-authors/ChestShop-3#50]
Error:
`[Craft Scheduler Thread - 399/WARN]: [ChestShop] Plugin ChestShop v3.8.12 generated an exception while executing task 33
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.Acrobot.ChestShop.Metrics.postPlugin(Metrics.java:335) ~[?:?]
	at com.Acrobot.ChestShop.Metrics.access$400(Metrics.java:57) ~[?:?]
	at com.Acrobot.ChestShop.Metrics$1.run(Metrics.java:223) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft.jar:git-Spigot-3fb9445-fbb47e8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [minecraft.jar:git-Spigot-3fb9445-fbb47e8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

My server version: Spigot 1.11.2

I found this method that can help, it is compatible with several versions: https://github.com/MrPowerGamerBR/PicoMoedas/blob/master/src/main/java/com/mrpowergamerbr/picomoedas/utils/RetroUtils.java

**Comment by Phoenix616** [comment]
What version of the plugin are you running? This should already be fixed in the [development builds](https://ci.minebench.de/job/ChestShop-3).
