### ISSUE TITLE
Can't buy/sell on 1.12-pre6 (paperspigot) (RESOLVED)

### ISSUE THREAD

**Issue by haugsvar** [ChestShop-authors/ChestShop-3#51]
[11:30:00] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ChestShop v3.8.13-SNAPSHOT (build #12)
org.bukkit.event.EventException: null
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:948) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) [patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:409) [patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.preparePreTransactionEvent(PlayerInteract.java:126) ~[?:?]
        at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:97) ~[?:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.12-pre6.jar:git-Paper-"bd34f206"]
        ... 18 more

**Comment by haugsvar** [comment]
Good news, it actually works in plain spigot 1.12. paperspigot not yet released.

[17:44:27 INFO]: This server is running CraftBukkit version git-Spigot-ede465d-bb4ae3b (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[17:44:27 INFO]: You are running the latest version
>ver chestshop
[17:44:34 INFO]: ChestShop version 3.8.13-SNAPSHOT (build #12)
[17:44:34 INFO]: A chest shop for economy plugins.
[17:44:34 INFO]: Authors: Acrobot and https://github.com/ChestShop-authors/ChestShop-3/contributors


[17:41:54 INFO]: [ChestShop] user_1 sold 1 Dirt for 10.00 to user_2 at [world] 209, 66, 350

**Comment by haugsvar** [comment]
#This issue can be marked as resolved
