### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Rukes** [ChestShop-authors/ChestShop-3#55]
Hello,
my sentry detected 2 errors, just reporting for fix (using latest #12 build).

`Could not pass event TransactionEvent to ChestShop v3.8.13-SNAPSHOT (build #12)
exception	org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:106)
	at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234)
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:448)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944)
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.Acrobot.Breeze.Utils.InventoryUtil.removeManually(InventoryUtil.java:230)
	at com.Acrobot.Breeze.Utils.InventoryUtil.remove(InventoryUtil.java:214)
	at com.Acrobot.ChestShop.Listeners.PostTransaction.ItemManager.removeItems(ItemManager.java:44)
	at com.Acrobot.ChestShop.Listeners.PostTransaction.ItemManager.shopItemRemover(ItemManager.java:24)
	at sun.reflect.GeneratedMethodAccessor676.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	... 25 more`

`
Could not pass event PlayerInteractEvent to ChestShop v3.8.13-SNAPSHOT (build #12)
exception	org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234)
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:448)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944)
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StackOverflowError
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:81)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131) -> and repeating many times`

Thanks :)

**Comment by Phoenix616** [comment]
The first error was fixed by commit 4abb9ae, please open a new issue with more info (like the full stack trace and ways to reproduce it) for the other error if it still occurs with the latest development build.
