### ISSUE TITLE
Error with 1.19.4

### ISSUE THREAD

**Issue by TheWeirdCoder** [ChestShop-authors/ChestShop-3#550]
### What is happening?

So i have the lastest development build and im trying to use it on 1.19.4 but it does not work. Here is the error below:

`[04:53:55 ERROR]: Error occurred while enabling ChestShop v3.12.3-SNAPSHOT (build 377) (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse.getProfiles()" because "response" is null
        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:59) ~[paper-1.19.4.jar:?]
        at com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfilesByNames(PaperGameProfileRepository.java:44) ~[paper-1.19.4.jar:git-Paper-482]
        at net.minecraft.server.players.GameProfileCache.lookupGameProfile(GameProfileCache.java:110) ~[?:?]
        at net.minecraft.server.players.GameProfileCache.get(GameProfileCache.java:181) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.getOfflinePlayer(CraftServer.java:1828) ~[paper-1.19.4.jar:git-Paper-482]
        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1262) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at com.Acrobot.ChestShop.UUIDs.NameManager.load(NameManager.java:347) ~[ChestShop.jar:?]
        at com.Acrobot.ChestShop.ChestShop.loadConfig(ChestShop.java:198) ~[ChestShop.jar:?]
        at com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:152) ~[ChestShop.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-482]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-482]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-482]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-482]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-482]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-482]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-482]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-482]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-482]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### What did you expect to happen?

I expected it to work fine since it was the lastest build

### Plugin Version

Lastest Dev build (cant do the cmd since it doesnt work)

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
 [Put the config here]
 ```

</details>

### Server Version

1.19.4

### Server Log

[idk what this file is I dont have it sorry :(]

### What other plugins are you running?

AdvancedBan, ArmorStandEditor, BanFromClaim, BetterConcrete, BetterRTP, ChestShop, Citizens, CoreProtect, CraftingStore, DecentHolograms, DiSky, EconomyShopGUI, FlappyAnticheat, GSit, GriefPrevention, HeadDB, ImageFrame, ItemEdit, LuckPerms, MarriageMaster, MiniMOTD, Multiverse-Core, MyPet, PlaceholderAPI, Plan, PlayerAuctions, PlayerWarps, PortableCraftingInvs, ProtocolLib, ServerUtils, SimpleRename, SkBee, Skript, SurvivalInvisiframes, TAB, UltraCosmetics, Vault, ViaBackwards, ViaVersion, VoidGen, Votifier, WorldEdit, WorldGuard, dynmap, eGlow, mcMMO, skRayFall, skript-gui and skript-votifier-hook

### Agreements

- [X] I have checked if there are already similar issues open.
- [x] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
This error is the server itself so please try an older or newer Paper build and see which version fixes it.

Also please provide your config.

**Comment by TheWeirdCoder** [comment]
i fixed it it was a stupid issue lol i forgot a economy plugin
