### ISSUE TITLE
Login exception

### ISSUE THREAD

**Issue by Rukes** [ChestShop-authors/ChestShop-3#57]
I am getting this error while player is joining server.

`[00:34:36 WARN]: [ChestShop] Plugin ChestShop v3.8.13-SNAPSHOT (build #14) generated an exception while executing task 187
java.lang.IllegalStateException: Both the "left-hand" and "right-hand" clauses have been defined. Did you miss an AND or OR?
at com.Acrobot.ChestShop.ORMlite.stmt.Where.appendSql(Where.java:581) ~[?:?]
at com.Acrobot.ChestShop.ORMlite.stmt.StatementBuilder.appendWhereStatement(StatementBuilder.java:158) ~[?:?]
at com.Acrobot.ChestShop.ORMlite.stmt.QueryBuilder.appendWhereStatement(QueryBuilder.java:476) ~[?:?]
at com.Acrobot.ChestShop.ORMlite.stmt.StatementBuilder.appendStatementString(StatementBuilder.java:140) ~[?:?]
at com.Acrobot.ChestShop.ORMlite.stmt.StatementBuilder.buildStatementString(StatementBuilder.java:123) ~[?:?]
at com.Acrobot.ChestShop.ORMlite.stmt.StatementBuilder.prepareStatement(StatementBuilder.java:74) ~[?:?]
at com.Acrobot.ChestShop.ORMlite.stmt.QueryBuilder.prepare(QueryBuilder.java:106) ~[?:?]
at com.Acrobot.ChestShop.ORMlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389) ~[?:?]
at com.Acrobot.ChestShop.ORMlite.stmt.Where.iterator(Where.java:538) ~[?:?]
at com.Acrobot.ChestShop.UUIDs.NameManager.storeUsername(NameManager.java:157) ~[?:?]
at com.Acrobot.ChestShop.Listeners.Player.PlayerConnect$1.run(PlayerConnect.java:28) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]`

**Comment by nitewing76** [comment]
I experience the same error with Build 14 (PaperSpigot 1.11.2)....the error also exists in #13, but not Build #12.

**Comment by Rukes** [comment]
Yup, I know. I am still using #12.

**Comment by Phoenix616** [comment]
Fixed on the [namemanager-v3](https://github.com/ChestShop-authors/ChestShop-3/tree/namemanager-v3) branch (build 17). Please note that this will convert your users.db to a new format (version 3) so make sure that you have backups if anything should happen. (Worked fine with several thousand users while testing though)
