### ISSUE TITLE
Folia 1.20.4 cannot be loaded 

### ISSUE THREAD

**Issue by cgw2023** [ChestShop-authors/ChestShop-3#587]
### What is happening?

using latest dev build 404 cannot be loaded on folia 1.20.4 version

### What did you expect to happen?

plugin able to load

### Plugin Version

ChestShop version 3.12.3-SNAPSHOT (build 404)

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
default plugin config, server is new
 ```

</details>

### Server Version

This server is running Folia version git-Folia-"e97b1ee" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: e97b1ee)

### Server Log

<details>
  <summary>Log</summary>

  ```
[17:46:48 ERROR]: Error occurred while enabling ChestShop v3.12.3-SNAPSHOT (build 404) (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:259) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:246) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:191) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:160) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at com.Acrobot.ChestShop.ChestShop.startUpdater(ChestShop.java:550) ~[ChestShop#404.jar:?]
        at com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:174) ~[ChestShop#404.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
  ```

</details>

### What other plugins are you running?

Vault

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by oAzzAo** [comment]
Thanks for posting I have the same problem and the same log output.

**Comment by cgw2023** [comment]
> Thanks for posting I have the same problem and the same log output.

found a solution
go to config.yml and set
```
TURN_OFF_UPDATE_NOTIFIER: true
TURN_OFF_DEV_UPDATE_NOTIFIER: true
```

**Comment by oAzzAo** [comment]
Thank you!

**Comment by Phoenix616** [comment]
You should really not close issues unless the underlaying bug was fixed.
