### ISSUE TITLE
Unable to buy (NullPointerException)

### ISSUE THREAD

**Issue by Rukes** [ChestShop-authors/ChestShop-3#59]
`[00:42:51 ERROR]: Could not pass event TransactionEvent to ChestShop v3.8.13-SNAPSHOT (build #17)
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:107) [ChestShop%20(3).jar:?]
at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:108) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:868) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-4df3c0c-03f1e37]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException`

**Comment by Phoenix616** [comment]
Did that happen on a fresh install or after you got the error from issue #58?
