### ISSUE TITLE
Error on migration

### ISSUE THREAD

**Issue by EvilOlaf** [ChestShop-authors/ChestShop-3#67]
```
[10:04:56] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.8.13-SNAPSHOT (build #26)
[10:04:56] [Server thread/INFO]: [ChestShop] Updating database...
[10:04:56] [Server thread/WARN]: [ChestShop] Fast accounts migration failed! (Could not run raw execute statement INSERT INTO `accounts` (name, shortName, uuid) SELECT name, shortName, uuid FROM `accounts-old`). Starting slow migration...
[10:08:55] [Server thread/ERROR]: [ChestShop] Could not load account PowerCrafter2000/PowerCrafter200/9da26f6a-efbe-40a8-8b5c-f77f58775aa3 to new database format
java.sql.SQLException: Unable to run insert stmt on object com.Acrobot.ChestShop.Database.Account@7d522e9a: INSERT INTO `accounts` (`name` ,`shortName` ,`uuid` ,`lastSeen` ) VALUES (?,?,?,?)
        at com.Acrobot.ChestShop.ORMlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ORMlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ORMlite.stmt.StatementExecutor.create(StatementExecutor.java:450) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.Database.Migrations.migrateTo3(Migrations.java:97) [ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.Database.Migrations.migrate(Migrations.java:44) [ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ChestShop.handleMigrations(ChestShop.java:182) [ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:94) [ChestShop-b26.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (column shortName is not unique)
        at org.sqlite.DB.newSQLException(DB.java:383) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.sqlite.DB.newSQLException(DB.java:387) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.sqlite.DB.execute(DB.java:342) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.sqlite.DB.executeUpdate(DB.java:363) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at com.Acrobot.ChestShop.ORMlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ORMlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[ChestShop-b26.jar:?]
        ... 17 more
[10:10:18] [Server thread/ERROR]: [ChestShop] Could not load account bludyreacegamer2/bludyreacegamer/e55d77cc-11d1-463e-8152-b9090d963e4f to new database format
java.sql.SQLException: Unable to run insert stmt on object com.Acrobot.ChestShop.Database.Account@34c8c500: INSERT INTO `accounts` (`name` ,`shortName` ,`uuid` ,`lastSeen` ) VALUES (?,?,?,?)
        at com.Acrobot.ChestShop.ORMlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ORMlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ORMlite.stmt.StatementExecutor.create(StatementExecutor.java:450) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.Database.Migrations.migrateTo3(Migrations.java:97) [ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.Database.Migrations.migrate(Migrations.java:44) [ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ChestShop.handleMigrations(ChestShop.java:182) [ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:94) [ChestShop-b26.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (column shortName is not unique)
        at org.sqlite.DB.newSQLException(DB.java:383) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.sqlite.DB.newSQLException(DB.java:387) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.sqlite.DB.execute(DB.java:342) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.sqlite.DB.executeUpdate(DB.java:363) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at com.Acrobot.ChestShop.ORMlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170) ~[ChestShop-b26.jar:?]
        at com.Acrobot.ChestShop.ORMlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[ChestShop-b26.jar:?]
        ... 17 more

```

Btw. I wouldn't be possible to let the mitigation run async to not lock up the server or get some kind a progress as this seems to take quite a while and I am unable to tell if the migration still running as expected or vor example run into a deadlock....

Running build 26 on Spigot 1.8.8

Edit: All right. For the statistics
```
[10:24:00] [Server thread/INFO]: [ChestShop] 83219 accounts successfully migrated. 5 accounts failed to migrate!
[10:24:00] [Server thread/INFO]: [ChestShop] Migration of accounts table finished in 1143.944s!
[10:24:00] [Server thread/WARN]: [ChestShop] Server economy account setting 'notrelevant' doesn't seem to be the name of a known player! Please log in at least once in order for the server economy account to work.
[10:24:00] [Server thread/INFO]: [ChestShop] LWC version 1.7.9 loaded.
[10:24:00] [Server thread/INFO]: [ChestShop] Vault loaded! Found an economy plugin!
```

**Comment by Phoenix616** [comment]
These errors are to expected if you have a lot of players while converting to the new format as the previous implementation did not check whether or not the short sign name was unique (which the new one does). I might make the error less noisy to avoid confusion in the future.

Adding a progress to the slow migration is a good idea, I'll look into that. (The normal migration in case of no short name conflicts should be a lot faster anyways)

**Comment by rautamiekka** [comment]
^ I imagine a status report every X seconds (assuming the process haven't finished sooner) would be the best, and maybe easiest to code.

Report every X records is a possibility.

**Comment by Phoenix616** [comment]
That commits adds a prettier error printing and an info every 60 seconds while the slow migration is running. Unfortunately doing it async isn't that easy to implement as the plugin heavily relies on the accounts data to properly work but I keep that in mind, maybe I find a good solution.
