### ISSUE TITLE
Could not pass event TransactionEvent to ChestShop v3.8.13-SNAPSHOT (build #30)

### ISSUE THREAD

**Issue by andris155** [ChestShop-authors/ChestShop-3#72]
```
[12:57:17] [Server thread/ERROR]: Could not pass event TransactionEvent to ChestShop v3.8.13-SNAPSHOT (build #30)
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[patched_1.12.1.jar:git-Paper-1179]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.1.jar:git-Paper-1179]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.1.jar:git-Paper-1179]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.1.jar:git-Paper-1179]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.1.jar:git-Paper-1179]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:105) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.12.1.jar:git-Paper-1179]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.1.jar:git-Paper-1179]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.1.jar:git-Paper-1179]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.1.jar:git-Paper-1179]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.1.jar:git-Paper-1179]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.12.1.jar:git-Paper-1179]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) ~[patched_1.12.1.jar:git-Paper-1179]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:949) ~[patched_1.12.1.jar:git-Paper-1179]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.1.jar:git-Paper-1179]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.1.jar:git-Paper-1179]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1179]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1179]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1179]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1179]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1179]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1179]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by Phoenix616** [comment]
This does not look like the full stacktrace of that error. Please look for a more complete one that should have happened earlier in your logs.

**Comment by Phoenix616** [comment]
No response in over two months. Closing this as no additional information has been provided.

**Comment by andris155** [comment]
I reset users.db and fixed this.

**Comment by Phoenix616** [comment]
It would be better if you would provide the missing information so that the issue can actually be fixed.
