### ISSUE TITLE
Plugin ChestShop v3.7.18 generated an exception while executing task 92023

### ISSUE THREAD

**Issue by TheDGOfficial** [ChestShop-authors/ChestShop-3#77]
Plugin version: ChestShop v3.7.18
Server version: 1.7.10 PaperSpigot

```[19:30:33] [Craft Scheduler Thread - 31/WARN]: Exception in thread "Craft Scheduler Thread - 31" 
[19:30:33] [Craft Scheduler Thread - 31/WARN]: org.apache.commons.lang.UnhandledException: Plugin ChestShop v3.7.18 generated an exception while executing task 92023
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Nodes must be provided.
	at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:168)
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:213)
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:35)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:161)
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:213)
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:35)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95)
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:271)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:262)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:234)
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:209)
	at com.Acrobot.ChestShop.Metadata.ItemDatabase.getItemCode(ItemDatabase.java:70)
	at com.Acrobot.Breeze.Utils.MaterialUtil$Metadata.getItemCode(MaterialUtil.java:355)
	at com.Acrobot.Breeze.Utils.MaterialUtil.getSignName(MaterialUtil.java:133)
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionLogger$1.run(TransactionLogger.java:34)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more```

**Comment by Phoenix616** [comment]
> Plugin ChestShop v3.7.18

You are running an outdated ChestShop version. Please test if this issue happens with the [latest development version](https://ci.minebench.de/job/ChestShop-3/).

**Comment by TheDGOfficial** [comment]
Latest development version is compatible with paper 1.7.10 ?

**Comment by Phoenix616** [comment]
You will have to test that, it might as well be but it's not tested. Should it be incompatible feel free to open a new issue and we will look into how much effort is required to make it compatible again. Beyond the latest version there is no support guaranteed though.

**Comment by Phoenix616** [comment]
No response, assume that it is not an issue on the latest versions. If it is please reopen this issue or a new one.
