### ISSUE TITLE
ChestShop is lagging my server

### ISSUE THREAD

**Issue by TheDGOfficial** [ChestShop-authors/ChestShop-3#85]
Timings:
![ekran goruntusu 19](https://user-images.githubusercontent.com/24778409/33232158-3080aaea-d212-11e7-9140-55cf7ff756ef.png)

PaperSpigot 1.7.10
ChestShop v3.8.12
Vault 1.4.1-b436
iConomy 7.0

**Comment by Phoenix616** [comment]
You are using an outdated build of ChestShop. The latest is 3.8.13 (build 40) and that should have some performance improvements. High VaultListener values are most likely caused by the economy system though.

Also the high InventoryItemMoveEvent count is due to some really resource intensive hopper calculation.

**Comment by TheDGOfficial** [comment]
What versions do you recommend for Vault and iConomy?
And, ChestShop's jenkins page contains 2 file. ChestShop and original-ChestShop.jar, which one should i download for my Paper 1.7.10 server?

**Comment by Phoenix616** [comment]
> What versions do you recommend for Vault and iConomy?
Always the latest. Also I didn't know iConomy was still active? My server switched to CraftConomy3 ages ago.

> And, ChestShop's jenkins page contains 2 file. ChestShop and original-ChestShop.jar, which one should i download for my Paper 1.7.10 server?
The ChestShop.jar. The -original one is the plugin without any dependencies shaded in so it will most likely not run. ;)

**Comment by TheDGOfficial** [comment]
Thank you. is craftconomy3 works in 1.7.10? and have a converter tool for iconomy?

**Comment by Phoenix616** [comment]
No idea if it works on such an outdated version. And it has an inbuild conversion from other economies. Generally speaking all economy plugins should work the same though.

**Comment by TheDGOfficial** [comment]
I getting this error from upgrading v3.8.12 to v.3.8.13 #40;

`[20:15:59] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.8.13-SNAPSHOT (build #40)
[20:15:59] [Server thread/INFO]: [ChestShop] Updating database...
[20:15:59] [Server thread/WARN]: java.sql.SQLException: Could not run raw execute statement ALTER TABLE `accounts` RENAME TO `accounts-old`
[20:15:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[20:15:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:606)
[20:15:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Database.Migrations.migrateTo3(Migrations.java:75)
[20:15:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.Database.Migrations.migrate(Migrations.java:44)
[20:15:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ChestShop.handleMigrations(ChestShop.java:182)
[20:15:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:94)
[20:15:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[20:15:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[20:15:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[20:15:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[20:15:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[20:15:59] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354)
[20:15:59] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328)
[20:15:59] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284)
[20:15:59] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227)
[20:15:59] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
[20:15:59] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[20:15:59] [Server thread/WARN]: Caused by: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: accounts)
[20:15:59] [Server thread/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[20:15:59] [Server thread/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[20:15:59] [Server thread/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[20:15:59] [Server thread/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[20:15:59] [Server thread/WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
[20:15:59] [Server thread/WARN]: 	at org.sqlite.Stmt.execute(Stmt.java:113)
[20:15:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.jdbc.JdbcDatabaseConnection.executeStatement(JdbcDatabaseConnection.java:122)
[20:15:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.stmt.StatementExecutor.executeRawNoArgs(StatementExecutor.java:420)
[20:15:59] [Server thread/WARN]: 	at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:604)
[20:15:59] [Server thread/WARN]: 	... 15 more
[20:15:59] [Server thread/INFO]: [ChestShop] Vault loaded! Found an economy plugin!`

**Comment by Phoenix616** [comment]
That should not be happening. Are you sure that you have a users.db? If so can you please provide that? If not, why does your version file claim that you have a version 2 database?

**Comment by TheDGOfficial** [comment]
I solved this problem and successfully updated to v3.8.13 but still lagging.
Also i updated the iconomy to iconomy recreation 7.8-stable.

Current versions:

Server: Paper 1.7.10
ChestShop: 3.8.13
iConomy Recreation: 7.8-stable(plugin.yml shows 7.9)
Vault: 1.4.1-b436

**Comment by Phoenix616** [comment]
Well if you are still getting issues then you might need to look at whether or not it's caused by a slow economy backend or your extremely outdated server version because there is not a lit more optimisation that can be done after the fixes that were introduced in build 37)

**Comment by TheDGOfficial** [comment]
I changed my economy plugin but chestshop is still lagging in timings.
![ekran goruntusu 32](https://user-images.githubusercontent.com/24778409/33673925-2a4d9cc2-dabf-11e7-92c8-5b33cf4eb451.png)
