### ISSUE TITLE
Error spam after last update.

### ISSUE THREAD

**Issue by TheDGOfficial** [ChestShop-authors/ChestShop-3#91]
I get this errors after the last development build update:

```
[02:03:52] [Server thread/ERROR]: Could not pass event BlockPistonRetractEvent to ChestShop v3.8.13-SNAPSHOT (build #42)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockPiston.e(BlockPiston.java:82) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockPiston.doPhysics(BlockPiston.java:46) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockDiodeAbstract.e(BlockDiodeAbstract.java:190) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneComparator.c(SourceFile:183) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneComparator.a(SourceFile:194) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.WorldServer.a(WorldServer.java:586) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.WorldServer.doTick(WorldServer.java:207) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:750) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.block.BlockPistonRetractEvent.getBlocks()Ljava/util/List;
	at com.Acrobot.ChestShop.Listeners.Block.Break.SignBreak.onBlockPistonRetract(SignBreak.java:90) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	... 192 more
```

**Comment by Phoenix616** [comment]
You are using an outdated server version. Unfortunately that doesn't have an API method that is necessary for the new slime block checks. I can add the old functionality back in that will be used when the new methods aren't found but that will be a bit less efficient.
