### ISSUE TITLE
PreTransactionEvent java.lang.Object cannot be cast to org.bukkit.inventory.ItemStack Error

### ISSUE THREAD

**Issue by TheDGOfficial** [ChestShop-authors/ChestShop-3#93]
ChestShop spams this error after last updates.

```[09:15:04] [Server thread/ERROR]: Could not pass event PreTransactionEvent to ChestShop v3.8.13-SNAPSHOT (build #46)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:99) [ChestShop.jar:?]
	at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:382) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:666) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.bukkit.inventory.ItemStack;
	at com.Acrobot.ChestShop.Listeners.PreTransaction.PartialTransactionModule.getItemsThatFit(PartialTransactionModule.java:270) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PreTransaction.PartialTransactionModule.onPreBuyTransaction(PartialTransactionModule.java:77) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor440.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	... 23 more```

**Comment by Phoenix616** [comment]
Should work now.

Please make sure to follow the issue template in the future and when you include logs use triple `
